const snacks = [
	{ id: 1, titolo: "Variabili e tipi", descrizione: "Dichiara variabili con let/const e stampa i loro tipi con typeof." },
	{ id: 2, titolo: "Operatori aritmetici", descrizione: "Calcola somma, sottrazione, moltiplicazione e divisione in una funzione." },
	{ id: 3, titolo: "Concatena stringhe", descrizione: "Unisci nome e cognome in una singola stringa usando template literal." },
	{ id: 4, titolo: "Template literals", descrizione: "Crea una stringa multilinea con variabili interpolate." },
	{ id: 5, titolo: "Parsing numeri", descrizione: "Usa parseInt e parseFloat su input stringa e gestisci NaN." },
	{ id: 6, titolo: "Array base", descrizione: "Crea un array, aggiungi/rimuovi elementi con push/pop." },
	{ id: 7, titolo: "Loop for", descrizione: "Itera un array e somma i suoi elementi con un for tradizionale." },
	{ id: 8, titolo: "for...of", descrizione: "Usa for...of per leggere i valori di un array." },
	{ id: 9, titolo: "forEach", descrizione: "Usa forEach per stampare ogni elemento dell'array." },
	{ id: 10, titolo: "map", descrizione: "Trasforma un array di numeri raddoppiandoli con map." },
	{ id: 11, titolo: "filter", descrizione: "Filtra i numeri pari usando filter." },
	{ id: 12, titolo: "reduce", descrizione: "Somma gli elementi di un array con reduce." },
	{ id: 13, titolo: "find e findIndex", descrizione: "Trova il primo elemento che soddisfa una condizione e il suo indice." },
	{ id: 14, titolo: "some ed every", descrizione: "Verifica se qualche elemento soddisfa la condizione e se tutti la soddisfano." },
	{ id: 15, titolo: "includes", descrizione: "Controlla se un array contiene un valore specifico." },
	{ id: 16, titolo: "Slice vs Splice", descrizione: "Esempio che mostra differenza tra slice (non muta) e splice (muta)." },
	{ id: 17, titolo: "Sort personalizzato", descrizione: "Ordina numeri in ordine decrescente passando una funzione a sort." },
	{ id: 18, titolo: "Join e split", descrizione: "Converti array in stringa con join e torna indietro con split." },
	{ id: 19, titolo: "Destructuring array", descrizione: "Estrai primi due elementi di un array con destructuring." },
	{ id: 20, titolo: "Destructuring oggetti", descrizione: "Estrai proprietà da un oggetto con destructuring e alias." },
	{ id: 21, titolo: "Parametri di funzione predefiniti", descrizione: "Definisci valori di default per parametri di funzione." },
	{ id: 22, titolo: "Rest e Spread (array)", descrizione: "Usa ... per concatenare array e per raccogliere argomenti (rest)." },
	{ id: 23, titolo: "Spread (oggetti)", descrizione: "Clona un oggetto e sovrascrivi una proprietà con spread." },
	{ id: 24, titolo: "Arrow functions", descrizione: "Riscrivi una funzione tradizionale come arrow function." },
	{ id: 25, titolo: "Scope e hoisting", descrizione: "Mostra differenza tra var, let e const riguardo allo scope." },
	{ id: 26, titolo: "Closure semplice", descrizione: "Crea una funzione che mantiene lo stato interno usando closure." },
	{ id: 27, titolo: "IIFE", descrizione: "Scrivi un Immediately Invoked Function Expression che stampa qualcosa." },
	{ id: 28, titolo: "Modulo semplice", descrizione: "Esporta/importa una funzione tra due moduli (CommonJS o ES Modules)." },
	{ id: 29, titolo: "Class basics", descrizione: "Definisci una classe con costruttore e metodo e crea un'istanza." },
	{ id: 30, titolo: "Inheritance (classi)", descrizione: "Crea sottoclasse che estende una classe base e usa super()." },
	{ id: 31, titolo: "Metodi statici", descrizione: "Aggiungi un metodo statico a una classe e chiamalo senza istanza." },
	{ id: 32, titolo: "Getter e setter", descrizione: "Definisci getter/setter per una proprietà di classe." },
	{ id: 33, titolo: "Error handling try/catch", descrizione: "Lancia un errore con throw e gestiscilo con try/catch." },
	{ id: 34, titolo: "Error personalizzato", descrizione: "Crea una classe che estende Error e usala." },
	{ id: 35, titolo: "Date basics", descrizione: "Crea una data, ottieni anno, mese e timestamp." },
	{ id: 36, titolo: "Intl per formattazione", descrizione: "Formatta una data o numero con Intl.DateTimeFormat/NumberFormat." },
	{ id: 37, titolo: "Regex semplice", descrizione: "Verifica se una stringa contiene solo numeri usando regex." },
	{ id: 38, titolo: "Regex replace", descrizione: "Sostituisci tutte le vocali in una stringa con '*' usando regex globale." },
	{ id: 39, titolo: "String methods", descrizione: "Uso di includes, startsWith, endsWith e slice su stringhe." },
	{ id: 40, titolo: "Immutabilità vs mutabilità", descrizione: "Esempio che mostra come modificare e non modificare dati." },
	{ id: 41, titolo: "Shallow vs Deep copy", descrizione: "Copia superficiale con spread e copia profonda con JSON.parse/stringify (limitata)." },
	{ id: 42, titolo: "Map (oggetto) vs Object", descrizione: "Usa Map per chiavi non-stringa e confrontalo con Object." },
	{ id: 43, titolo: "Set base", descrizione: "Crea un Set per rimuovere duplicati da un array." },
	{ id: 44, titolo: "WeakMap e WeakSet", descrizione: "Spiega breve uso e limitazioni di WeakMap/WeakSet." },
	{ id: 45, titolo: "JSON stringify/parse", descrizione: "Serializza un oggetto e deserializzalo di nuovo." },
	{ id: 46, titolo: "LocalStorage (browser)", descrizione: "Salva e recupera una stringa da localStorage (sezione browser)." },
	{ id: 47, titolo: "SessionStorage", descrizione: "Esempio analogo a localStorage ma per sessione corrente." },
	{ id: 48, titolo: "Fetch API base", descrizione: "Effettua una richiesta GET a un'API pubblica e leggi il JSON." },
	{ id: 49, titolo: "POST con fetch", descrizione: "Invia dati JSON con fetch usando metodo POST e headers appropriati." },
	{ id: 50, titolo: "AbortController", descrizione: "Annulla una richiesta fetch in corso con AbortController." },
	{ id: 51, titolo: "Promise basics", descrizione: "Crea una Promise manuale e risolvila o rigettala." },
	{ id: 52, titolo: "Promise chaining", descrizione: "Concatena then per trasformare risultati asincroni." },
	{ id: 53, titolo: "Promise.all e Promise.race", descrizione: "Esempio che mostra differenze tra all e race." },
	{ id: 54, titolo: "Async/Await", descrizione: "Riscrivi una catena di Promise usando async/await." },
	{ id: 55, titolo: "Handling errors con async", descrizione: "Gestisci errori di una funzione async con try/catch." },
	{ id: 56, titolo: "Event loop (concetti)", descrizione: "Spiega microtask vs macrotask con esempi di setTimeout e Promise." },
	{ id: 57, titolo: "setTimeout e setInterval", descrizione: "Usa setTimeout per delay e clearInterval per fermare un interval." },
	{ id: 58, titolo: "Debounce", descrizione: "Implementa debounce per limitare chiamate ripetute (input)." },
	{ id: 59, titolo: "Throttle", descrizione: "Implementa throttle per limitare esecuzioni ripetute." },
	{ id: 60, titolo: "Event delegation", descrizione: "Usa event delegation per gestire click su elementi dinamici." },
	{ id: 61, titolo: "DOM selection", descrizione: "Seleziona elementi con querySelector e querySelectorAll." },
	{ id: 62, titolo: "Manipolare classList", descrizione: "Aggiungi/rimuovi/toggle classi con classList." },
	{ id: 63, titolo: "Creare elementi DOM", descrizione: "Crea un elemento, impostane testo e inseriscilo nella pagina." },
	{ id: 64, titolo: "Event listeners", descrizione: "Aggiungi e rimuovi listener con addEventListener/removeEventListener." },
	{ id: 65, titolo: "Form basics", descrizione: "Gestisci submit di un form e previeni comportamento predefinito." },
	{ id: 66, titolo: "Validazione form", descrizione: "Valida campi (required, pattern) e mostra messaggi all'utente." },
	{ id: 67, titolo: "File API (browser)", descrizione: "Leggi un file input e mostra anteprima immagine usando FileReader." },
	{ id: 68, titolo: "Drag and Drop", descrizione: "Implementa drag & drop base per spostare elementi nella pagina." },
	{ id: 69, titolo: "Canvas basics", descrizione: "Disegna un rettangolo su canvas 2D." },
	{ id: 70, titolo: "Web Storage avanzato", descrizione: "Serializza strutture complesse e gestisci versioning dei dati locali." },
	{ id: 71, titolo: "Web Workers", descrizione: "Esegui elaborazioni in background con un Web Worker semplice." },
	{ id: 72, titolo: "Service Worker (concept)", descrizione: "Spiega come un service worker può cacheare risorse offline." },
	{ id: 73, titolo: "IndexedDB (concetti)", descrizione: "Salva oggetti complessi lato client usando IndexedDB (introduzione)." },
	{ id: 74, titolo: "Import dinamico", descrizione: "Carica moduli dinamicamente usando import() asincrono." },
	{ id: 75, titolo: "Polyfill e transpiling", descrizione: "Spiega perché usare polyfill e strumenti come Babel." },
	{ id: 76, titolo: "Event target e propagation", descrizione: "Esempio di event bubbling e stopPropagation." },
	{ id: 77, titolo: "Custom events", descrizione: "Crea e dispatcha un CustomEvent con dati personalizzati." },
	{ id: 78, titolo: "Profiling e performance", descrizione: "Usa console.time per misurare performance di una funzione." },
	{ id: 79, titolo: "Memory leaks comuni", descrizione: "Esempi di come i riferimenti globali possono causare memory leak." },
	{ id: 80, titolo: "Security: XSS basics", descrizione: "Mostra come evitare XSS sanitizzando input prima di inserire HTML." },
	{ id: 81, titolo: "CSP (concetti)", descrizione: "Breve spiegazione di Content Security Policy per limitare esecuzione codice." },
	{ id: 82, titolo: "CORS (concetti)", descrizione: "Spiega in breve Cross-Origin Resource Sharing e come il server abilita le richieste." },
	{ id: 83, titolo: "JWT basics", descrizione: "Concetti base di JSON Web Token e verifica lato client (solo demo)." },
	{ id: 84, titolo: "Fetch con autorizzazione", descrizione: "Esempio di header Authorization con fetch per chiamate protette." },
	{ id: 85, titolo: "Moduli CSS-in-JS (concetti)", descrizione: "Breve presentazione di tecniche per stilare componenti con JS." },
	{ id: 86, titolo: "Functional programming (concetti)", descrizione: "Immutabilità, funzioni pure e uso di map/filter/reduce." },
	{ id: 87, titolo: "Currying", descrizione: "Trasforma una funzione in più funzioni parziali (esempio semplice)." },
	{ id: 88, titolo: "Composition", descrizione: "Componi funzioni semplici per creare comportamenti più complessi." },
	{ id: 89, titolo: "Memoization", descrizione: "Implementa memoization per ottimizzare funzioni costose." },
	{ id: 90, titolo: "Generators", descrizione: "Crea un generator function che produce una sequenza di numeri." },
	{ id: 91, titolo: "Symbol", descrizione: "Crea Symbol e usalo come chiave unica in un oggetto." },
	{ id: 92, titolo: "Reflect e Proxy", descrizione: "Esempio base di Proxy per intercettare get/set su un oggetto." },
	{ id: 93, titolo: "BigInt", descrizione: "Usa BigInt per lavorare con interi maggiori di Number.MAX_SAFE_INTEGER." },
	{ id: 94, titolo: "Intl.Collator", descrizione: "Confronta stringhe con regole di lingua locali usando Intl.Collator." },
	{ id: 95, titolo: "LocaleCompare", descrizione: "Ordina array di stringhe rispettando la lingua con localeCompare." },
	{ id: 96, titolo: "ECMAScript versions", descrizione: "Breve panoramica delle feature principali introdotte in ES6+." },
	{ id: 97, titolo: "Testing unitario (concetti)", descrizione: "Scrivi un semplice test unitario per una funzione usando assert o Jest." },
	{ id: 98, titolo: "Console avanzato", descrizione: "Usa console.table, console.group e console.time per debugging." },
	{ id: 99, titolo: "CLI Node.js base", descrizione: "Crea uno script Node che accetta argomenti da riga di comando." },
	{ id: 100, titolo: "Deploy minore", descrizione: "Procedure rapide per pubblicare una semplice app static su Netlify o GitHub Pages." }
];

export default snacks;

